# Project information
site_name: Jimfs JUnit Jupiter
site_url: https://stefano.codes/jimfs-junit-jupiter
site_author: Stefano Cordio
site_description: JUnit Jupiter `@TempDir` extension based on the in-memory file system Jimfs

site_dir: target/mkdocs

# Fail with warnings
strict: true

# Repository
repo_url: https://github.com/scordio/jimfs-junit-jupiter

# Copyright
copyright: Copyright &copy; 2024-2025 Stefano Cordio

# Configuration
theme:
  name: material
  features:
    - content.code.copy
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  logo: assets/images/logo-white.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

# Plugins
plugins:
  - search
  - social:
      cards_layout: default/variant

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/scordio.github.io
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@scordio
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/stefanocodes
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/scordio/

# Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path:
        - src/demo/java/io/github/scordio
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Extra stylesheets
extra_css:
  - stylesheets/extra.css
  - stylesheets/pygments-intellij.css

# Page tree
nav:
  - index.md
  - usage.md
  - configuration-parameters.md
  - limitations.md
  - javadoc.md
  - release-notes.md
